
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.mohammedia.enset.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod(operationName = "ListComptes")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListComptes", targetNamespace = "http://ws.mohammedia.enset.ma/", className = "proxy.ListComptes")
    @ResponseWrapper(localName = "ListComptesResponse", targetNamespace = "http://ws.mohammedia.enset.ma/", className = "proxy.ListComptesResponse")
    @Action(input = "http://ws.mohammedia.enset.ma/BanqueService/ListComptesRequest", output = "http://ws.mohammedia.enset.ma/BanqueService/ListComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod(operationName = "Consulter")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Consulter", targetNamespace = "http://ws.mohammedia.enset.ma/", className = "proxy.Consulter")
    @ResponseWrapper(localName = "ConsulterResponse", targetNamespace = "http://ws.mohammedia.enset.ma/", className = "proxy.ConsulterResponse")
    @Action(input = "http://ws.mohammedia.enset.ma/BanqueService/ConsulterRequest", output = "http://ws.mohammedia.enset.ma/BanqueService/ConsulterResponse")
    public Compte consulter(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEuroToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEuroToDh", targetNamespace = "http://ws.mohammedia.enset.ma/", className = "proxy.ConversionEuroToDh")
    @ResponseWrapper(localName = "ConversionEuroToDhResponse", targetNamespace = "http://ws.mohammedia.enset.ma/", className = "proxy.ConversionEuroToDhResponse")
    @Action(input = "http://ws.mohammedia.enset.ma/BanqueService/ConversionEuroToDhRequest", output = "http://ws.mohammedia.enset.ma/BanqueService/ConversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
